[package]
name = "storage"
version = "6.7.2-beta.1"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.32", features = ["full"] }
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
tower = "0.4"
tracing = "0.1"
async-recursion = "1.0"
rand = "0.8"
opendal = { features = [
    "services-rocksdb",
    "services-moka",
], git = "https://github.com/apache/incubator-opendal" }

cloud-util = "0.8.0-beta.1"
cita_cloud_proto = "=6.7.2-beta.1"
# opendal disable the default-features of rocksdb, we need to enable it manually
rocksdb = "0.21"

[[bin]]
name = "bench"
path = "benches/main.rs"

[dev-dependencies]
tempfile = "3.7"
quickcheck = "1.0"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
