[[bin]]
name = 'bench'
path = 'benches/main.rs'

[package]
name = 'storage'
version = '6.7.1-beta1'
license = 'Apache-2.0'
edition = '2021'
authors = ['Rivtower Technologies <contact@rivtower.com>']

[dependencies]
tonic = '0.9'
prost = '0.11'
hex = '0.4'
serde = '1.0'
serde_derive = '1.0'
tower = '0.4'
tracing = '0.1'
async-recursion = '1.0'
rand = '0.8'
rocksdb = '0.21'
cloud-util = '=0.7.1-beta1'
cita_cloud_proto = '=6.7.1-beta1'

[dependencies.clap]
version = '4.3'
features = ['derive']

[dependencies.tokio]
version = '1.29'
features = ['full']

[dependencies.opendal]
version = '0.38'
features = ['services-rocksdb']

[dev-dependencies]
tempfile = '3.6'
quickcheck = '1.0'
[profile.release]
debug = 1
[profile.release.package."*"]
debug = 0
